#!/usr/local/bin/perl

print ("Enter a number:\n");
$number1 = <STDIN>;
chop ($number1);
print ("Enter another number:\n");
$number2 = <STDIN>;
chop ($number2);
if ($number2 == 0) {
	print("Error: can't divide by zero\n");
}
elsif ($number1 == 0) {
	print("output value: ", $number1, "\n");
}
else  {
	$out_val = $number1 / $number2;
	print("output value: ", $out_val, "\n");
}
