#!/usr/local/bin/perl

$var = 0;
while ($var <= @ARGV-1) {
	$size = -s $ARGV[$var];
	if($size > 10000) {
		print("File $ARGV[$var] is larger than 10000 byte\n");
	}
	else {
		print("File $ARGV[$var] is smaller than 10000 byte\n");
	}
	$var++;
}
