#!/usr/local/bin/perl

print("Text input:\n");
@input = <STDIN>;

while($var < @input) {
	$text = $input[$var];
	@_0_matches = $text =~ /0/g;
	@_1_matches = $text =~ /1/g;
	@_2_matches = $text =~ /2/g;
	@_3_matches = $text =~ /3/g;
	@_4_matches = $text =~ /4/g;
	@_5_matches = $text =~ /5/g;
	@_6_matches = $text =~ /6/g;
	@_7_matches = $text =~ /7/g;
	@_8_matches = $text =~ /8/g;
	@_9_matches = $text =~ /9/g;
	$_0_sum += @_0_matches;
	$_1_sum += @_1_matches;
	$_2_sum += @_2_matches;
	$_3_sum += @_3_matches;
	$_4_sum += @_4_matches;
	$_5_sum += @_5_matches;
	$_6_sum += @_6_matches;
	$_7_sum += @_7_matches;
	$_8_sum += @_8_matches;
	$_9_sum += @_9_matches;
	$var++;
}

$total = $_0_sum*0 + $_1_sum*1 + $_2_sum*2 + $_3_sum*3 + $_4_sum*4 +
 		 $_5_sum*5 + $_6_sum*6 + $_7_sum*7 + $_8_sum*8 + $_9_sum*9 + 1;

print("sum-up plus1: $total\n");
