#!/usr/local/bin/perl

$value = 1234567890;
print ("first value is ", $value, "\n");
$value = 1234567890123456;
print ("second value is ", $value, "\n");
$value = 12345678901234567890;
print ("third value is ", $value, "\n");
$value = 12345678901234567890123;
print ("fourth value is ", $value, "\n");
