#!/usr/local/bin/perl
#Rewrite the following statement using the conditional operator:
#if ($var1 == 5 || $var2 == 7) {
#$result = $var1 * $var2 + 16.5;
#} else {
#print("condition is false\n");
#$result = 0;
#}

$result = ($var1 == 5 || $var2 == 7) ? $var1 * $var2 + 16.5 : 0;
$outstring = ($var1 == 5 || $var2 == 7) ? "" : "condition is false\n";
print($outstring);

